### ISSUE TITLE
Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by lipekhan** [webchain-network/webchain-wallet#104]
``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/lipe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///C:/Users/lipe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
    at file:///C:/Users/lipe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
 ```

**Comment by danangfebrian** [comment]
same here, pls help.
