### ISSUE TITLE
Invalid Sender - Sending web to other web accounts 

### ISSUE THREAD

**Issue by scarsman** [webchain-network/webchain-wallet#122]
[2019-06-24 08:39:53.798] [error] screenActions - Show error JsonRpcError: Invalid sender
    at JsonRpcError.ExtendableBuiltin (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24767:30)
    at new JsonRpcError (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24796:116)
    at file:///opt/WebchainWallet/resources/app.asar/app/index.js:24833:19
    at <anonymous>

**Comment by scarsman** [comment]
I switch to windows and used the latest wallet and its working now. In linux the error still persists `Failed to fetch ` during import json account
