### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S

### ISSUE THREAD

**Issue by hajhesam** [webchain-network/webchain-wallet#13]
``` 
JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/UnanimouS/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:23896:30)
    at new JsonRpcError (file:///C:/Users/UnanimouS/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:23925:116)
    at file:///C:/Users/UnanimouS/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:23962:19
    at <anonymous>
 ```

**Comment by maoxs2** [comment]
Same error
The error was: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S

How to deal?

**Comment by horaciojesusgg** [comment]
Hello! This happend with specific transaction hashed that contains leading zeroes. This will be fixed in one of the libraries used in the project.

**Comment by danielwebimp** [comment]
This issue is duplicated. https://github.com/webchain-network/webchain-wallet/issues/128 . So I can close this one.
