### ISSUE TITLE
Invalid address length, expected 40 got 2 bytes

### ISSUE THREAD

**Issue by parsajafari87** [webchain-network/webchain-wallet#162]
``` 
JsonRpcError: Invalid address length, expected 40 got 2 bytes
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by danielwebimp** [comment]
Hi, please check your wallet address and make it's correct.
