### ISSUE TITLE
Invalid data format: Missing passphrase

### ISSUE THREAD

**Issue by trudertube** [webchain-network/webchain-wallet#168]
``` 
JsonRpcError: Invalid data format: Missing passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25590:30)
    at new JsonRpcError (file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25619:116)
    at file:///C:/Program%20Files/WebchainWallet/resources/app.asar/app/index.js:25656:19
 ```

**Comment by trudertube** [comment]
oh sorry... i forgot the password

**Comment by danielwebimp** [comment]
Ok, good that you noticed it. Thanks
