### ISSUE TITLE
Cannot read property 'plus' of null

### ISSUE THREAD

**Issue by olliloehr** [webchain-network/webchain-wallet#169]
``` 
TypeError: Cannot read property 'plus' of null
    at file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:115171:33
    at updateInDeepMap (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4185:22)
    at updateInDeepMap (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4194:23)
    at List.Map.updateIn (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3492:26)
    at List.Map.update (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3484:14)
    at file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:115054:23
    at updateInDeepMap (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4185:22)
    at updateInDeepMap (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4194:23)
    at Map.updateIn (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3492:26)
    at Map.update (file:///C:/Users/Olli/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3484:14)
 ```

**Comment by danielwebimp** [comment]
Hi, please can you explain how to reproduce this error? If possible, could you try to reproduce it with new wallet release? Specify also the operating system.

**Comment by olliloehr** [comment]
Startet the Wallet while Mining.1 hour before, i Had a netframe Update from Windows 10 ( dont know exactly which one). And the AMD drivers.Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [webchain-network/webchain-wallet] Cannot read property 'plus' of null (#169)Von: danielwebimp An: webchain-network/webchain-wallet Cc: olliloehr ,Author Hi, please can you explain how to reproduce this error? If possible, could you try to reproduce it with new wallet release? Specify also the operating system.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/webchain-network/webchain-wallet/issues/169?email_source=notifications\u0026email_token=ANRLIUSAEWKLTUJEO53IY7TQUJIPPA5CNFSM4JLTYRX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEJUTUQ#issuecomment-554912210",
"url": "https://github.com/webchain-network/webchain-wallet/issues/169?email_source=notifications\u0026email_token=ANRLIUSAEWKLTUJEO53IY7TQUJIPPA5CNFSM4JLTYRX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEJUTUQ#issuecomment-554912210",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by danielwebimp** [comment]
Hi, thanks for the information provided. You must run the wallet as Administrator and select a remote node 1 or 2 http://joxi.ru/l2Zg3XOhE8v0oA instead of the full node. Make sure that your firewall allows the wallet to access internet. And by the same time, you should be able to run your miner to optimize resources allocated to the miner. Because when you select Full Node and you run the miner, it's like you are mining twice.
