### ISSUE TITLE
Invalid sender

### ISSUE THREAD

**Issue by anti950819** [webchain-network/webchain-wallet#174]
``` 
JsonRpcError: Invalid sender
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/dolgozo/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24027:30)
    at new JsonRpcError (file:///C:/Users/dolgozo/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24056:116)
    at file:///C:/Users/dolgozo/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24093:19
    at <anonymous>
 ```

**Comment by anti950819** [comment]
I can't send webchain to my friend. When I try send webchain the wallet give me a error. (invalid sender)

**Comment by danielwebimp** [comment]
Hi, please check again your destination address. There should be an error, if the address is correct, you won't get any error

**Comment by anti950819** [comment]
Where can i find this "destination address"?
