### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by d5tails** [webchain-network/webchain-wallet#42]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Garrin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24027:30)
    at new JsonRpcError (file:///C:/Users/Garrin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24056:116)
    at file:///C:/Users/Garrin/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:24093:19
    at <anonymous>
 ```

**Comment by d5tails** [comment]
please can you assist , cant send Webchain to stex

**Comment by d5tails** [comment]
ANY HELP HERE

**Comment by horaciojesusgg** [comment]
Hi! This issue was already addressed. The team is working on a new version of the wallet to fix this and other bugs.

Regards!
