### ISSUE TITLE
Cannot read property 'plus' of null

### ISSUE THREAD

**Issue by alangrau** [webchain-network/webchain-wallet#48]
``` 
TypeError: Cannot read property 'plus' of null
    at file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:73844:33
    at updateInDeepMap (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4276:22)
    at updateInDeepMap (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4285:23)
    at List.Map.updateIn (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3583:26)
    at List.Map.update (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3575:14)
    at file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:73747:23
    at updateInDeepMap (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4276:22)
    at updateInDeepMap (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:4285:23)
    at Map.updateIn (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3583:26)
    at Map.update (file:///C:/Users/Alan/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:3575:14)
 ```

**Comment by alangrau** [comment]
This error occurred when I tried to select "view->reload" on the wallet application.
