### ISSUE TITLE
Invalid sender

### ISSUE THREAD

**Issue by edstewbob** [webchain-network/webchain-wallet#86]
``` 
JsonRpcError: Invalid sender
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/ed/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///C:/Users/ed/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
    at file:///C:/Users/ed/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
 ```

**Comment by edstewbob** [comment]
Trying to send 1000 web   I get this same error when trying to send to the same address on myetherwallet after providing either my private address or my json/password.

**Comment by edstewbob** [comment]
My bad I didn't upgrade to the latest release of the wallet.
